In [132]:
import os

In [133]:
path_dir =os.listdir("./")

In [134]:
path = "./"+path_dir[1]
name_files_list = os.listdir(path)

In [135]:
import pandas as pd

In [136]:
train_df = pd.read_csv(path+"/train.tsv", delimiter='\t')
train_df.head()

PhraseId  SentenceId                                             Phrase  \
0         1           1  A series of escapades demonstrating the adage ...   
1         2           1  A series of escapades demonstrating the adage ...   
2         3           1                                           A series   
3         4           1                                                  A   
4         5           1                                             series   

   Sentiment  
0          1  
1          2  
2          2  
3          2  
4          2

In [137]:
train = train_df['Phrase'].values.tolist()
train_df['Sentiment'].unique()

array([1, 2, 3, 4, 0], dtype=int64)

In [144]:
test_df = pd.read_csv(path+"/train.tsv", delimiter='\t')
test_df.head()
c = test_df['Phrase'].tolist()
c =[len(i.split()) for i in c]
print(c)

[37, 14, 2, 1, 1, 12, 1, 11, 1, 10, 3, 1, 2, 1, 1, 7, 1, 6, 1, 5, 1, 4, 1, 3, 1, 2, 1, 23, 22, 2, 1, 20, 19, 18, 3, 2, 1, 1, 15, 3, 1, 2, 1, 12, 1, 11, 1, 10, 1, 9, 1, 8, 7, 6, 1, 5, 1, 4, 1, 3, 2, 1, 1, 11, 7, 1, 6, 5, 1, 4, 3, 2, 1, 1, 1, 1, 4, 3, 2, 1, 1, 21, 7, 2, 1, 1, 5, 4, 3, 1, 2, 1, 1, 1, 14, 4, 3, 2, 1, 1, 10, 9, 1, 8, 1, 7, 3, 2, 1, 1, 4, 1, 3, 1, 2, 1, 26, 25, 16, 4, 3, 1, 2, 1, 1, 12, 11, 2, 1, 9, 1, 8, 7, 1, 6, 5, 1, 4, 3, 2, 1, 1, 9, 8, 4, 3, 2, 1, 1, 1, 4, 3, 1, 2, 1, 1, 7, 6, 1, 5, 2, 1, 3, 2, 1, 1, 19, 6, 2, 1, 4, 3, 2, 1, 1, 1, 13, 12, 5, 1, 4, 1, 3, 2, 1, 1, 7, 1, 6, 3, 2, 1, 1, 3, 1, 2, 1, 1, 10, 1, 9, 8, 3, 1, 2, 1, 1, 5, 4, 3, 2, 1, 1, 20, 2, 1, 18, 17, 1, 16, 2, 1, 14, 1, 13, 1, 12, 1, 11, 1, 10, 1, 9, 1, 8, 1, 7, 2, 1, 5, 1, 4, 2, 1, 2, 1, 1, 9, 8, 7, 6, 2, 1, 1, 4, 2, 1, 1, 2, 9, 8, 7, 1, 6, 2, 1, 4, 3, 2, 1, 1, 22, 1, 21, 20, 7, 6, 5, 1, 4, 3, 1, 2, 1, 1, 13, 1, 12, 11, 1, 10, 5, 3, 2, 1, 1, 2, 1, 1, 5, 2, 1, 3, 2, 1, 1, 30, 2, 1, 1, 28, 27, 16, 15, 14, 13, 7

In [124]:
a =train_df['Phrase'].tolist()
a = [i.split() for i in a]
b = [len(i) for i in a]
max(b)

52

In [13]:
train_df['SentenceId'].unique()
# 8544 句子

array([   1,    2,    3, ..., 8542, 8543, 8544], dtype=int64)

In [14]:
print(train_df['PhraseId'])
train_df['PhraseId'].unique()

0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10
10            11
11            12
12            13
13            14
14            15
15            16
16            17
17            18
18            19
19            20
20            21
21            22
22            23
23            24
24            25
25            26
26            27
27            28
28            29
29            30
           ...  
156030    156031
156031    156032
156032    156033
156033    156034
156034    156035
156035    156036
156036    156037
156037    156038
156038    156039
156039    156040
156040    156041
156041    156042
156042    156043
156043    156044
156044    156045
156045    156046
156046    156047
156047    156048
156048    156049
156049    156050
156050    156051
156051    156052
156052    156053
156053    156054
156054    156055
156055    156056
156056    156057
156057    1560

array([     1,      2,      3, ..., 156058, 156059, 156060], dtype=int64)

In [15]:
sub_df = pd.read_csv(path+"/sampleSubmission.csv")

In [16]:
sub_df

PhraseId  Sentiment
0        156061          2
1        156062          2
2        156063          2
3        156064          2
4        156065          2
5        156066          2
6        156067          2
7        156068          2
8        156069          2
9        156070          2
10       156071          2
11       156072          2
12       156073          2
13       156074          2
14       156075          2
15       156076          2
16       156077          2
17       156078          2
18       156079          2
19       156080          2
20       156081          2
21       156082          2
22       156083          2
23       156084          2
24       156085          2
25       156086          2
26       156087          2
27       156088          2
28       156089          2
29       156090          2
...         ...        ...
66262    222323          2
66263    222324          2
66264    222325          2
66265    222326          2
66266    222327          2
66267    222328          2
66268    222329          2
66269    222330          2
66270    222331          2
66271    222332          2
66272    222333          2
66273    222334          2
66274    222335          2
66275    222336          2
66276    222337          2
66277    222338          2
66278    222339          2
66279    222340          2
66280    222341          2
66281    222342          2
66282    222343          2
66283    222344          2
66284    222345          2
66285    222346          2
66286    222347          2
66287    222348          2
66288    222349          2
66289    222350          2
66290    222351          2
66291    222352          2

[66292 rows x 2 columns]

In [17]:
a = train_df['Sentiment'].value_counts()
print(a.values,list(a.index))

[79582 32927 27273  9206  7072] [2, 3, 1, 4, 0]


In [18]:
import matplotlib.pyplot as plt
plt.bar(list(a.index), a.values)
plt.show()

<Figure size 640x480 with 1 Axes>

In [19]:
from sklearn.utils import shuffle

In [20]:
s = ([[1,2,3],[4,3,2],[12,3,34]],[1,2,4])

In [21]:
x, y =s
shuffle(x, y)

[[[4, 3, 2], [1, 2, 3], [12, 3, 34]], [2, 1, 4]]

In [22]:
from collections import defaultdict
op = defaultdict(int)
op[1]

0

In [23]:
def iter_num():
    for i in range(10):
        yield i,i+1
g = iter_num()


In [24]:
import os
print(os.getcwd())

D:\celeba4\project_env\base_nlp\data


In [25]:
import json

In [26]:
p = [[1,2], [2, 3]]
dir_pth = os.path.join(os.path.dirname(os.getcwd()), "source")
file_pth = os.path.join(dir_pth, 'test.json')

f = open(file_pth, 'w')
json.dump(p, f, indent=2, ensure_ascii=False)
f.close()

In [77]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer
enc=LabelBinarizer()
ab = enc.fit_transform(np.array([1,2,3,4,0,4]))
ab

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]])

In [75]:
a = np.array([[1, 2, 5, 6]])
def softmax(x):
    temp =[]
    for sample in x:
        e_x = np.exp(sample - np.max(sample))
        temp.append(e_x/e_x.sum())
    return np.array(temp)

In [64]:
#r = softmax(a)
r = softmax(a)
r

array([[0.00483724, 0.01314897, 0.26410418, 0.71790961]])

In [65]:
resu = np.argmax(r, axis=1)
resu

array([3], dtype=int64)

In [66]:
def softmax2(x):
    e_x =x
    return e_x/e_x.sum()

In [67]:
print(a)
softmax(a)

[[1 2 5 6]]


array([[0.00483724, 0.01314897, 0.26410418, 0.71790961]])

In [69]:
print(softmax(a))
print(np.array([[1,0,0,0]])*np.log(softmax(a)))

[[0.00483724 0.01314897 0.26410418 0.71790961]]
[[-5.33141162 -0.         -0.         -0.        ]]


In [32]:
import datetime
a = datetime.datetime.now()
print(a.year)

2021


In [33]:
print(a.month, a.day, a.hour, a.minute, a.second)

8 31 16 3 11


In [44]:
np.argmax([3,12,2])

1

In [70]:
Data = np.array([[1,2, 3],[4,5,6]])
Data.shape

(2, 3)

In [76]:
ab.shape

(6, 5)

In [103]:
A = np.array([[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0]])
B = np.array([[1,0,0,0,0],[0,1,0,0,0],[1,0,0,0,0]])

In [107]:
correct=0
(A!=B).sum()/2

1.0

In [99]:
correct

0

In [108]:
len(A)

3

In [128]:
np.array([1,4]).shape

(2,)

In [131]:
a = [[1,2],[3,4],[2,3]]
b = np.array(a)
b[:2].shape

(2, 2)

In [149]:
np.array(np.array([[1,0,0,0],[0,1,0,0]])!=np.array([[1,0,0,0], [1,0,0,0]])).sum()/2

1.0

In [155]:
 def softmax(x):
        """
        activate func:　using of classification
        :param x: (16, 5)
        :return:
        """
        ex_list = []
        for sample in x:
            e_x = np.exp(sample - np.max(sample))
            ex_list.append(e_x/e_x.sum())
        return ex_list

In [156]:
softmax(np.array([[0,1,2,0,1]]))

[array([0.06745081, 0.1833503 , 0.49839779, 0.06745081, 0.1833503 ])]